//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qwert1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int StorageID { get; set; }
        public int TypeID { get; set; }
        public int IngredientsD { get; set; }
        public int SupplierID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Type Type { get; set; }
    }
}
